package vista;

import controlador.Pelea;
import modelo.Personaje;
import javax.swing.JEditorPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LinaCostanza
 */
public class battle extends javax.swing.JFrame {

    /**
     * Creates new form battle
     */
    public battle() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        vidaboss.setMaximum(pjb.getVida());
        vidalobo.setMaximum(pjb1.getVida());
        vidamedusa.setMaximum(pjb2.getVida());
        vidaescorpion.setMaximum(pjb3.getVida());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        vidaescorpion = new javax.swing.JProgressBar();
        vidalobo = new javax.swing.JProgressBar();
        vidamedusa = new javax.swing.JProgressBar();
        vidamonstruo = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 710));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/escorpion.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 100, 260, 250);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lobo.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 350, 250, 170);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/medusa_1.gif"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 530, 190, 170);

        jButton1.setText("ataque");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 420, 80, 23);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("lobo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 400, 70, 14);

        jButton4.setText("ataque");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(270, 600, 80, 23);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("medusa");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 580, 80, 14);

        jButton9.setText("ataque");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(270, 240, 90, 23);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("escorpion");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 220, 70, 14);
        getContentPane().add(vidaescorpion);
        vidaescorpion.setBounds(230, 320, 146, 14);
        getContentPane().add(vidalobo);
        vidalobo.setBounds(240, 480, 146, 14);
        getContentPane().add(vidamedusa);
        vidamedusa.setBounds(240, 640, 146, 14);
        getContentPane().add(vidamonstruo);
        vidamonstruo.setBounds(570, 600, 146, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("monstruo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(560, 340, 70, 14);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/monster.gif"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(534, 294, 250, 290);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo batalla.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 800, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.escenario.atacar1(1);
      this.vidalobo.setValue(pjb1.getVida());
       this.vidamonstruo.setValue(pjm.getVida());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       escenario.atacar2(1);
       vidamedusa.setValue(pjb2.getVida());
       vidamonstruo.setValue(pjm.getVida());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        escenario.atacar3(1);
        vidaescorpion.setValue(pjb3.getVida());
        vidamonstruo.setValue(pjm.getVida());
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new battle().setVisible(true);
            }
        });
    }
            

    
            Personaje pjb1 = new Personaje(200, 100, 500, 150, "guerrero", "Lobo");
    
            Personaje pjb2 = new Personaje(150, 150, 550, 250, "curandera", "Medusa");
   
            Personaje pjb3 = new Personaje(172,170 , 480, 300, "asesino", "Escorpion");
            
            Personaje pjm = new Personaje((int)(Math.random()*170)+50,(int) 
                    (Math.random()*120),(int) (Math.random()*600)+200,(int) (Math.random()*270)+100, null, "Monstruo");
            
            Pelea escenario = new Pelea(pjb1, pjb2, pjb3, pjm);
   
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar vidaescorpion;
    private javax.swing.JProgressBar vidalobo;
    private javax.swing.JProgressBar vidamedusa;
    private javax.swing.JProgressBar vidamonstruo;
    // End of variables declaration//GEN-END:variables
}
